stages:
  - validate

before_script:
    - ./scripts/circleci-install-packer.sh

validate:
  stage: validate
  script:
    - ./packer/packer validate ./packer.json
  tags:
    - bionic
    - lxd
    - lxc
