stages:
  - validate

before_script:
    - ./scripts/gitlabci-install-packer.sh

validate:
  stage: validate
  script:
    - ./packer/packer validate ./packer.json
  tags:
    - bionic

build-base:
  stage: build-base
  script:
    - ./scripts/gitlabci-install-lxd.sh
    - ./scripts/gitlabci-build-base.sh
  tags:
    - bionic
    - lxd
    - lxc
