stages:
  - validate
  - build-base

before_script:
    - ./scripts/gitlabci-install-packer.sh

validate:
  stage: validate
  script:
    - ./packer/packer validate ./packer.json
  tags:
    - bionic

build-base:
  stage: build-base
  script:
    - BUILD_VERSION=0.0.1 BUILD_COMMIT_SHA=$CI_COMMIT_SHA ./scripts/gitlabci-build-base.sh
  tags:
    - bionic
    - lxd
    - lxc
